species = {
  'Brassica': [
    'Brassica, Forage',
    'Mustard',
    'Radish, Forage',
    'Radish, Oilseed',
    'Rape, Oilseed',
    'Rapeseed, Forage',
    'Turnip, Forage',
    'Turnip, Purple Top',
  ],
  'Broadleaf': [
    'Phacelia',
    'Sunflower',
  ],
  'Grass': [
    'Barley',
    'Cereal Rye',
    'Millet, Foxtail',
    'Millet, Japanese',
    'Millet, Pearl',
    'Oats',
    'Ryegrass, Annual',
    'Ryegrass, Perennial',
    'Sorghum',
    'Sorghum-sudangrass',
    'Sudangrass',
    'Teff',
    'Triticale',
    'Wheat',
  ],
  'Legume': [
    'Alfalfa, Dormant',
    'Clover, Alsike',
    'Clover, Balansa',
    'Clover, Berseem',
    'Clover, Crimson',
    'Clover, Red',
    'Clover, White',
    'Cowpea',
    'Pea',
    'Sunn Hemp',
    'Sweetclover, Yellow',
    'Vetch, Hairy',
  ],
}
